### ISSUE TITLE
Any idea for dbaas supporting this lib ?

### ISSUE THREAD

**Issue by theobat** [df7cb/postgresql-unit#23]
This library is awesome, thanks for the good work. I asked on heroku-postgres support why it's not available on their solution, they answered that to get an extension supported, it has to be vetted by official PostgreSQL developers and verified by heroku to ensure there is no data corruption. Do you think this would be possible ?

More generally do you think this extension could be integrated in dbaas (amazon, azure, compose, elephantSQL etc) without problems ?

**Comment by df7cb** [comment]
Hi,
sorry for the late reply, somehow I didn't notice any mail notifcation.

What would "vetted by official PostgreSQL developers" mean? I'm a PostgreSQL Contributor (https://www.postgresql.org/community/contributors/) if that counts. About the data corruption, there's a testsuite. :)

Generally, making the extension available on whatever platform shouldn't pose any problems because it doesn't do anything security-relevant.

(Closing the issue as I have little influence on what platforms are doing.)

**Comment by theobat** [comment]
hey, thanks for the answer digital ocean recently opened a dbaas with support for postgresql-unit if anyone is wondering (none of the others are supporting it, yet, though).

**Comment by df7cb** [comment]
Interesting to know. Thanks!
